### ISSUE TITLE
Schreibfehler

### ISSUE THREAD

**Issue by behrends** [thomafe/GenericBananaMachine#1]
prove statt proove
https://github.com/thomafe/GenericBananaMachine/blob/a9c0181c327b3ba389e251d6a72974c5f06b7d60/src/view/Output.java#L35

**Comment by thomafe** [comment]
Ist auf dem development branch gefixt, danke.
Wird aber erst im master auftauchen, wenn wir mit der nächsten Version fertig sind.
#fb8403fbd4fe578a21738a7dbbe85b8efcda6a25 (on branch development)

Mfg Felix
