### ISSUE TITLE
Kein Ausweg aus der Höhle

### ISSUE THREAD

**Issue by behrends** [thomafe/GenericBananaMachine#10]
Nur zur Info, falls dies nicht bekannt ist. Ich bin in die Höhle gegangen und komme dort nicht weiter. Ich erhalte für alle Befehle die gleiche Ausgabe:

```

Help
Your flashlight is too low for this darkness. You need something to check if there is anything.
Do you want to "use" an item or do you want to "leave"?
These items are in your inventory:
 - Signal Rocket
 - Compass

Look around
Your flashlight is too low for this darkness. You need something to check if there is anything.
Do you want to "use" an item or do you want to "leave"?
These items are in your inventory:
 - Signal Rocket
 - Compass

Use Compass
Your flashlight is too low for this darkness. You need something to check if there is anything.
Do you want to "use" an item or do you want to "leave"?
These items are in your inventory:
 - Signal Rocket
 - Compass
```

**Comment by thomafe** [comment]
Danke fürs Feedback, allerdings ist dies kein Fehler.
Sie sind in eine Passage gegangen und haben nicht das korrekte Item. Also wäre "leave" der richtige Befehl, um zurück in die Höle zu gehen. Backtracking ist teil des Spiels.
Die gewöhnlichen Befehler funktionieren hier nicht, wir werden die Ausgabe und Situationsbeschreibungen anpassen, dass es nicht wieder zu solchen Verwirrungen kommt.

>use tunnel entrance
Your flashlight is too low for this darkness. You need something to check if there is anything.
Do you want to use an item or do you want to "leave"?
These items are in your inventory:
Cloth | Compass
 leave
You decided to go back
