### ISSUE TITLE
Unnötiger Vergleich mit Boolean-Variable

### ISSUE THREAD

**Issue by behrends** [thomafe/GenericBananaMachine#5]
`additionalItemResolved` ist bereits vom Typ `boolean` und muss daher nicht explizit mit `== true` überprüft werden:

https://github.com/thomafe/GenericBananaMachine/blob/8eec97db9823a223b6b7af69902544986300baad/src/model/Obstacle.java#L104

(Dies wurde in IntelliJ mit `Analyze` > `Inspect Code…` gefunden)

**Comment by simone273** [comment]
Die Methode tryToUseItem ist jetzt nicht mehr in der Klasse Obstacle sondern in ItemObstacle und DoubleItemObstacle. Dort habe ich aber sichergestelllt, dass das Problem nicht vorhanden ist.
