### ISSUE TITLE
Leeres Interface

### ISSUE THREAD

**Issue by behrends** [thomafe/GenericBananaMachine#7]
https://github.com/thomafe/GenericBananaMachine/blob/8eec97db9823a223b6b7af69902544986300baad/src/model/superclasses/Approachable.java#L1-L6

Werden hier noch Methoden eingefügt?

Falls etwas in Arbeit ist, dann kann es z.B. in einem Kommentar mit `TODO` oder `WIP` (*work in progress*) markiert werden.

**Comment by thomafe** [comment]
Die gehört zu einem Feature was in weiter Ferne steht. Falls beim nächsten Release noch nix drin steht fliegt es wieder raus

**Comment by thomafe** [comment]
Wurde gelöscht. Falls wir es später brauchen, kommts wieder rein.
