### ISSUE TITLE
Alles aufgehoben --> angeblich liegt noch einiges herum

### ISSUE THREAD

**Issue by behrends** [thomafe/GenericBananaMachine#9]
Nachdem ich am Beach alles aufgehoben habe (Rope, Machete, Flashlight) und ich `Look around` ausführe wird immer noch folgendes ausgegeben:

```
You look around and see a bunch of equipment stuff laying on the ground.
```

(ist vielleicht nicht wirklich ein Bug aber etwas verwirrend)

**Comment by thomafe** [comment]
Danke. Ja die Beschreiung eines Ortes ist statisch. Das erste Level hat einige inkonsistente/verwirrende Beschreibungen. In zukünftigen Levels wird mehr darauf geachtet, konsistente und unmissverständliche Beschreibungen zu liefern.
